"""create leave module tables

Revision ID: 05e9d936f3cc
Revises: 2277e8b40676
Create Date: 2025-12-19 18:43:13.265591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '05e9d936f3cc'
down_revision: Union[str, Sequence[str], None] = '2277e8b40676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'leave_types' not in tables:
        op.create_table('leave_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('leave_type', sa.String(length=100), nullable=False),
        sa.Column('short_code', sa.String(length=20), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.Column('modified_by', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_leave_types_id'), 'leave_types', ['id'], unique=False)
    
    if 'leave_config' not in tables:
        op.create_table('leave_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('leave_type_id', sa.Integer(), nullable=False),
        sa.Column('per_month', sa.Integer(), nullable=False),
        sa.Column('no_of_leaves', sa.Integer(), nullable=False),
        sa.Column('carry_forward', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.Column('modified_by', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_leave_config_id'), 'leave_config', ['id'], unique=False)
    
    if 'leave_balances' not in tables:
        op.create_table('leave_balances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('leave_type_id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('allocated', sa.Float(), nullable=False),
        sa.Column('used', sa.Float(), nullable=False),
        sa.Column('pending', sa.Float(), nullable=False),
        sa.Column('balance', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.Column('modified_by', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'leave_type_id', 'year', name='uq_leave_balance_user_type_year')
        )
        op.create_index('idx_leave_balance_user_year', 'leave_balances', ['user_id', 'year'], unique=False)
        op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    
    leave_master_cols = [c['name'] for c in inspector.get_columns('leave_master')]
    if 'leave_type_id' not in leave_master_cols:
        op.add_column('leave_master', sa.Column('leave_type_id', sa.Integer(), nullable=False))
    if 'leave_days' not in leave_master_cols:
        op.add_column('leave_master', sa.Column('leave_days', sa.Float(), nullable=False))
    
    # Check if the foreign key constraint already exists before creating
    # Note: Alembic's op.create_foreign_key doesn't have an 'if_not_exists' parameter.
    # A more robust check would involve inspecting existing foreign keys,
    # but for simplicity, we'll assume if the columns are added, the FK should be too.
    # If the FK creation fails, it might indicate a previous partial migration.
    existing_fks = inspector.get_foreign_keys('leave_master')
    fk_exists = any(fk['name'] == 'fk_leave_master_type' for fk in existing_fks)
    if not fk_exists and 'leave_type_id' in leave_master_cols: # Only try to create if column exists
        op.create_foreign_key('fk_leave_master_type', 'leave_master', 'leave_types', ['leave_type_id'], ['id'])
        
    if 'balance' in leave_master_cols:
        op.drop_column('leave_master', 'balance')
    if 'carry_forward' in leave_master_cols:
        op.drop_column('leave_master', 'carry_forward')
    if 'allocated' in leave_master_cols:
        op.drop_column('leave_master', 'allocated')
    if 'used' in leave_master_cols:
        op.drop_column('leave_master', 'used')
    if 'leave_type' in leave_master_cols:
        op.drop_column('leave_master', 'leave_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    leave_master_cols = [c['name'] for c in inspector.get_columns('leave_master')]
    if 'leave_type' not in leave_master_cols:
        op.add_column('leave_master', sa.Column('leave_type', mysql.VARCHAR(length=50), nullable=False))
    if 'used' not in leave_master_cols:
        op.add_column('leave_master', sa.Column('used', mysql.INTEGER(), autoincrement=False, nullable=True))
    if 'allocated' not in leave_master_cols:
        op.add_column('leave_master', sa.Column('allocated', mysql.INTEGER(), autoincrement=False, nullable=True))
    if 'carry_forward' not in leave_master_cols:
        op.add_column('leave_master', sa.Column('carry_forward', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    if 'balance' not in leave_master_cols:
        op.add_column('leave_master', sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=True))
    
    # Check if the foreign key constraint exists before dropping
    existing_fks = inspector.get_foreign_keys('leave_master')
    fk_exists = any(fk['name'] == 'fk_leave_master_type' for fk in existing_fks)
    if fk_exists:
        op.drop_constraint('fk_leave_master_type', 'leave_master', type_='foreignkey')
    
    if 'leave_days' in leave_master_cols:
        op.drop_column('leave_master', 'leave_days')
    if 'leave_type_id' in leave_master_cols:
        op.drop_column('leave_master', 'leave_type_id')
        
    if 'leave_balances' in tables:
        # Check if indexes exist before dropping
        existing_indexes = inspector.get_indexes('leave_balances')
        if any(idx['name'] == op.f('ix_leave_balances_id') for idx in existing_indexes):
            op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
        if any(idx['name'] == 'idx_leave_balance_user_year' for idx in existing_indexes):
            op.drop_index('idx_leave_balance_user_year', table_name='leave_balances')
        op.drop_table('leave_balances')
    if 'leave_config' in tables:
        existing_indexes = inspector.get_indexes('leave_config')
        if any(idx['name'] == op.f('ix_leave_config_id') for idx in existing_indexes):
            op.drop_index(op.f('ix_leave_config_id'), table_name='leave_config')
        op.drop_table('leave_config')
    if 'leave_types' in tables:
        existing_indexes = inspector.get_indexes('leave_types')
        if any(idx['name'] == op.f('ix_leave_types_id') for idx in existing_indexes):
            op.drop_index(op.f('ix_leave_types_id'), table_name='leave_types')
        op.drop_table('leave_types')
    # ### end Alembic commands ###
