"""add_trial_period_and_payment_method_features

Revision ID: 693c034c329a
Revises: 4901a7a3f83e
Create Date: 2026-01-08 17:20:36.484702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '693c034c329a'
down_revision: Union[str, Sequence[str], None] = '4901a7a3f83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('payment_gateway', sa.String(length=20), nullable=False),
    sa.Column('gateway_customer_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_method_id', sa.String(length=100), nullable=True),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_expiry_month', sa.Integer(), nullable=True),
    sa.Column('card_expiry_year', sa.Integer(), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.add_column('organizations', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('trial_start_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('trial_end_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('trial_days', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('payments', sa.Column('billing_cycle', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('payment_gateway', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('gateway_payment_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('gateway_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('gateway_signature', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('gateway_metadata', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'payments', ['gateway_order_id'])
    op.create_foreign_key(None, 'payments', 'payment_methods', ['payment_method_id'], ['id'])
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', mysql.VARCHAR(length=512), nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'gateway_metadata')
    op.drop_column('payments', 'gateway_signature')
    op.drop_column('payments', 'gateway_order_id')
    op.drop_column('payments', 'gateway_payment_id')
    op.drop_column('payments', 'payment_gateway')
    op.drop_column('payments', 'billing_cycle')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'payment_method_id')
    op.drop_column('organizations', 'trial_days')
    op.drop_column('organizations', 'trial_end_date')
    op.drop_column('organizations', 'trial_start_date')
    op.drop_column('organizations', 'is_trial')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
