"""extra fields to test_reports table

Revision ID: a56076ac653b
Revises: 79878089200d
Create Date: 2025-12-26 11:10:01.182031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a56076ac653b'
down_revision: Union[str, Sequence[str], None] = '79878089200d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_master', sa.Column('leave_type_id', sa.Integer(), nullable=False))
    op.add_column('leave_master', sa.Column('leave_days', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'leave_master', 'leave_types', ['leave_type_id'], ['id'])
    op.drop_column('leave_master', 'carry_forward')
    op.drop_column('leave_master', 'allocated')
    op.drop_column('leave_master', 'used')
    op.drop_column('leave_master', 'leave_type')
    op.drop_column('leave_master', 'balance')
    op.add_column('test_reports', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('test_reports', sa.Column('errors', sa.JSON(), nullable=True))
    op.add_column('test_reports', sa.Column('execution_time', sa.String(length=50), nullable=False))
    # op.add_column('test_reports', sa.Column('framework', sa.String(length=50), nullable=True))
    op.add_column('test_reports', sa.Column('environment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_reports', 'environment')
    # op.drop_column('test_reports', 'framework')
    op.drop_column('test_reports', 'execution_time')
    op.drop_column('test_reports', 'errors')
    op.drop_column('test_reports', 'created_by')
    op.add_column('leave_master', sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_master', sa.Column('leave_type', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('leave_master', sa.Column('used', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_master', sa.Column('allocated', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_master', sa.Column('carry_forward', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leave_master', type_='foreignkey')
    op.drop_column('leave_master', 'leave_days')
    op.drop_column('leave_master', 'leave_type_id')
    # ### end Alembic commands ###
