"""extra fields to test_reports table

Revision ID: a56076ac653b
Revises: 79878089200d
Create Date: 2025-12-26 11:10:01.182031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'a56076ac653b'
down_revision: Union[str, Sequence[str], None] = '79878089200d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # ### commands auto generated by Alembic - please adjust! ###
    test_reports_cols = [c['name'] for c in inspector.get_columns('test_reports')]
    
    if 'created_by' not in test_reports_cols:
        op.add_column('test_reports', sa.Column('created_by', sa.String(length=255), nullable=False))
    if 'errors' not in test_reports_cols:
        op.add_column('test_reports', sa.Column('errors', sa.JSON(), nullable=True))
    if 'execution_time' not in test_reports_cols:
        op.add_column('test_reports', sa.Column('execution_time', sa.String(length=50), nullable=False))
    if 'environment' not in test_reports_cols:
        op.add_column('test_reports', sa.Column('environment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # ### commands auto generated by Alembic - please adjust! ###
    test_reports_cols = [c['name'] for c in inspector.get_columns('test_reports')]
    
    if 'environment' in test_reports_cols:
        op.drop_column('test_reports', 'environment')
    if 'execution_time' in test_reports_cols:
        op.drop_column('test_reports', 'execution_time')
    if 'errors' in test_reports_cols:
        op.drop_column('test_reports', 'errors')
    if 'created_by' in test_reports_cols:
        op.drop_column('test_reports', 'created_by')
    # ### end Alembic commands ###
