"""create a modules table

Revision ID: b9b845bcd0a7
Revises: fc20b1fdeb0d
Create Date: 2026-01-02 18:39:00.828082

"""
"""create a modules table

Revision ID: b9b845bcd0a7
Revises: fc20b1fdeb0d
Create Date: 2026-01-02 18:39:00.828082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'b9b845bcd0a7'
down_revision: Union[str, Sequence[str], None] = 'fc20b1fdeb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'modules' not in tables:
        op.create_table('modules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    
    leave_cols = [c['name'] for c in inspector.get_columns('leave_master')]
    if 'leave_type_id' not in leave_cols:
        op.add_column('leave_master', sa.Column('leave_type_id', sa.Integer(), nullable=False))
    if 'leave_days' not in leave_cols:
        op.add_column('leave_master', sa.Column('leave_days', sa.Float(), nullable=False))
    
    existing_fks = inspector.get_foreign_keys('leave_master')
    if not any(fk['name'] == 'fk_leave_master_type_b9b8' for fk in existing_fks) and 'leave_type_id' in leave_cols:
         # Use a unique name for this PK if possible or check if it exists
         try:
             op.create_foreign_key('fk_leave_master_type_b9b8', 'leave_master', 'leave_types', ['leave_type_id'], ['id'])
         except:
             pass

    if 'carry_forward' in leave_cols: op.drop_column('leave_master', 'carry_forward')
    if 'balance' in leave_cols: op.drop_column('leave_master', 'balance')
    if 'used' in leave_cols: op.drop_column('leave_master', 'used')
    if 'allocated' in leave_cols: op.drop_column('leave_master', 'allocated')
    if 'leave_type' in leave_cols: op.drop_column('leave_master', 'leave_type')

    menu_cols = [c['name'] for c in inspector.get_columns('menus')]
    if 'module_id' not in menu_cols:
        op.add_column('menus', sa.Column('module_id', sa.Integer(), nullable=False))
        op.create_foreign_key('fk_menus_module', 'menus', 'modules', ['module_id'], ['id'])

    report_cols = [c['name'] for c in inspector.get_columns('test_reports')]
    if 'created_by' not in report_cols:
        op.add_column('test_reports', sa.Column('created_by', sa.String(length=255), nullable=False))
    if 'errors' not in report_cols:
        op.add_column('test_reports', sa.Column('errors', sa.JSON(), nullable=True))
    if 'execution_time' not in report_cols:
        op.add_column('test_reports', sa.Column('execution_time', sa.String(length=50), nullable=False))
    if 'environment' not in report_cols:
        op.add_column('test_reports', sa.Column('environment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    report_cols = [c['name'] for c in inspector.get_columns('test_reports')]
    if 'environment' in report_cols: op.drop_column('test_reports', 'environment')
    if 'execution_time' in report_cols: op.drop_column('test_reports', 'execution_time')
    if 'errors' in report_cols: op.drop_column('test_reports', 'errors')
    if 'created_by' in report_cols: op.drop_column('test_reports', 'created_by')
    
    menu_cols = [c['name'] for c in inspector.get_columns('menus')]
    if 'module_id' in menu_cols:
        op.drop_constraint('fk_menus_module', 'menus', type_='foreignkey')
        op.drop_column('menus', 'module_id')
        
    leave_cols = [c['name'] for c in inspector.get_columns('leave_master')]
    if 'leave_type' not in leave_cols: op.add_column('leave_master', sa.Column('leave_type', mysql.VARCHAR(length=50), nullable=False))
    if 'allocated' not in leave_cols: op.add_column('leave_master', sa.Column('allocated', mysql.INTEGER(), autoincrement=False, nullable=True))
    if 'used' not in leave_cols: op.add_column('leave_master', sa.Column('used', mysql.INTEGER(), autoincrement=False, nullable=True))
    if 'balance' not in leave_cols: op.add_column('leave_master', sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=True))
    if 'carry_forward' not in leave_cols: op.add_column('leave_master', sa.Column('carry_forward', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    
    if 'leave_type_id' in leave_cols:
        try:
            op.drop_constraint('fk_leave_master_type_b9b8', 'leave_master', type_='foreignkey')
        except:
            pass
        op.drop_column('leave_master', 'leave_days')
        op.drop_column('leave_master', 'leave_type_id')
        
    if 'modules' in tables:
        op.drop_index(op.f('ix_modules_id'), table_name='modules')
        op.drop_table('modules')
    # ### end Alembic commands ###
