from app.models.user_m import User
from app.models.role_m import Role
from app.models.course_m import Course
from app.models.video_m import Video
from app.models.QuizCheckpoint_m import QuizCheckpoint
from app.models.QuizHistory_m import QuizHistory
from app.models.Progress_m import Progress
from app.models.organization_m import *
from app.models.branch_m import Branch
from app.models.category_m import Category
from app.models.salary_structure_m import SalaryStructure
from app.models.payroll_m import Payroll
from app.models.formula_m import Formula
from app.models.permission_m import Permission
from app.models.attendance_summary_m import Attendance
from app.models.payroll_attendance_m import PayrollAttendance
from app.models.candidate_documents_m import CandidateDocument
from app.models.candidate_m import Candidate
from app.models.job_posting_m import JobPosting
from app.models.job_description_m import JobDescription
from app.models.leavemaster_m import LeaveMaster
from app.models.shift_change_request_m import ShiftChangeRequest
from app.models.user_shifts_m import UserShift
from app.models.notification_m import Notification
from app.models.menu_m import *
from app.models.role_right_m import *
from app.models.shift_roster_m import *
from app.models.week_day_m import *
from app.models.shift_roster_detail_m import *
from app.models.subscription_plans_m import *
from app.models.add_on_m import *
from app.models.organization_add_on_m import *
from app.models.payment_m import *
from app.models.payment_method_m import PaymentMethod
from app.models.holiday_m import *
from app.models.shift_m import Shift
from app.models.department_m import Department
from app.models.attendance_punch_m import AttendancePunch
from app.models.leavetype_m import LeaveType
from app.models.leaveconfig_m import LeaveConfig
from app.models.leave_balance_m import LeaveBalance
from app.models.enrollment_m import Enrollment
from app.models.subscription_plan_module_m import SubscriptionPlanModule
from app.models.test_report_m import TestReport
from app.models.module_m import Module